export default {
   categories: {
      "animals": { name: "Animals &amp; Pets" },
      "baby": { name: "Baby Products" },
      "books_media": { name: "Books and Media" },
      "arts_crafts": { name: "Arts and Crafts" },
      "skincare": { name: "Beauty and Skincare" },
      "building": { name: "Building and Construction" },
      "daily_essentials": { name: "Daily Essentials" },
      "education": { name: "Education" },
      "groceries": { name: "Groceries" },
      "drinks": { name: "Drinks" },
      "fashion": { name: "Fashion" },
      "mens_fashion": { name: "Mens Fashion" },
      "womens_fashion": { name: "Womens Fashion" },
      "kids_fashion": { name: "Kids Fashion" },
      "fitness": { name: "Gym and Fitness" },
      "electronics": { name: "Electronics" },
      "food": { name: "Food &amp; Beverages" },
      "home": { name: "Home &amp; Kitchen" },
      "gaming": { name: "Gaming" },
      "health": { name: "Health &amp; Pharmaceuticals" },
      "cosmetics": { name: "Makeup and Cosmetics" },
      "insurance": { name: "Insurance" },
      "office": { name: "Office Equipment" },
      "personal_care": { name: "Personal Care" },
      "phones_tablets": { name: "Phones and Tablets" },
      "services": { name: "Professional Services" },
      "restaurant": { name: "Restaurant" },
      "supermarket": { name: "Supermarket" },
      "toys": { name: "Toys &amp; Games" },
      "others": { name: "Others" },
   },
}
